---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-traffic
  labels:
    app: emojify-traffic
spec:
  replicas: 5
  selector:
    matchLabels:
      app: emojify-traffic
  template:
    metadata:
      labels:
        app: emojify-traffic
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      containers:
      - name: load-test
        image: nicholasjackson/emojify-traffic:v0.2.1
        env:
        - name: BASE_URI
          value: http://ingress
        - name: DURATION
          value: "1m"
        - name: SHOW_PROGRESS
          value: "false"
        - name: USERS
          value: "3"
